### ISSUE TITLE
Use Datasource pattern instead of viewControllers list

### ISSUE THREAD

**Issue by pieterclaerhout** [AlKhokhlov/SwiftyPageController#1]
If you have a lot of view controllers, it's probably a lot better to use the datasource pattern (similar to collection and table views). This would avoid the overhead of having to first instantiate all view controllers before the page controller can be shown.

It should be using a lot less memory as well as it wouldn't have to load all view controllers in memory at once...

**Comment by alkhokhlov** [comment]
Thanks for your attention. I think dataSource pattern isn't correct, because you need to save data(if loaded from network), save contentOffset(if tableView, collectionView). Furthermore, you only need to load viewController classes. Views are being loaded only when you show them.

DataSource will be good idea if you need to implement something like UIPageViewController, where you need similar view for all controllers.
